#!/bin/bash
BASE_DIR=$(cd $(dirname $0);pwd)
HEAD="CentOS7_RPMS"
ARCH_NAME="$HEAD_$1.7z"
PART_DIR="$BASE_DIR/pub/$HEAD/$1"

make_part() {
  [ -d $PART_DIR ] && rm -rf $PART_DIR
  mkdir -p $PART_DIR
  chmod a+rx $PART_DIR

  md5sum $ARCH_NAME.* | tee $PART_DIR/md5.txt
  for f in $ARCH_NAME.*
  do
    NUM=$(echo $f | grep -o 0..)
    7z a -mx0 -v50m $PART_DIR/$NUM/part.7z $f
  done

  pushd $PART_DIR > /dev/null
  find . -type f | sed -e 's/^.\///' | sort | tee files.txt
  popd > /dev/null
}

[ -d $BASE_DIR/tmp ] && rm -rf $BASE_DIR/tmp
mkdir -p $BASE_DIR/tmp

pushd $BASE_DIR/tmp > /dev/null
case "$1" in
  os|updates|extras)
    7z a -mx0 -v1g $ARCH_NAME $BASE_DIR/linux/centos/7/$1
    make_part
    ;;
  epel)
    7z a -mx0 -v1g $ARCH_NAME $BASE_DIR/linux/fedora/$1
    make_part
    ;;
  *)
    echo "Usage: $0 [os|updates|extras|epel]"
    ;;
esac
popd > /dev/null
