#!/bin/bash
REPOS_DIR=$(cd $(dirname $0);pwd)
SERVER=http://ftp.iij.ad.jp

case "$1" in
  os|updates|extras)
    REPOS="linux/centos/7/$1/x86_64"
    echo ">>> download $REPOS"
    lftp -e "mirror --delete --only-newer /pub/$REPOS/ $REPOS_DIR/$REPOS/ && exit" $SERVER
    ;;
  epel)
    REPOS="linux/fedora/epel/7/x86_64"
    echo ">>> download $REPOS"
    lftp -e "mirror --delete --only-newer -X $REPOS/debug/* /pub/$REPOS/ $REPOS_DIR/$REPOS/ && exit" $SERVER
    ;;
esac
