#!/bin/bash

rm ./CentOS7_RPMS.7z.*
rm -rf ./arch

7z a -v1g CentOS7_RPMS.7z ./CentOS ./Fedora
chmod a+rx ./arch

for f in ./CentOS7_RPMS.7z.*
do
  NUM=$(echo $f | grep -o 0..)
  7z a -mx0 -v50m ./arch/$NUM/data.7z $f
done

md5sum ./CentOS7_RPMS.7z.* > ./arch/md5.txt

pushd arch
find . -type f | sed -e 's/^.\///' | sort | tee files.txt
popd

cat <<'EOS' > arch/Get-yum_repos.ps1
$src = "http://www11234ui.sakura.ne.jp/yum_repos"
$dst = "$Env:PUBLIC\Downloads\yum_repos"

$count = (cat files.txt).count
$index = 1
cat files.txt | %{
  Write-Progress -Activity "CentOS7 RPMS" -Status "($index/$count) $_" -PercentComplete (100.0 * $index / $count)

  $dir = Split-Path "$dst\$_"
  if (!(Test-Path $dir)) { md -fo $dir }

  Start-BitsTransfer "$src/$_" "$dst\$_"
  $index++
}
EOS
